version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - equilib_network

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile.dev
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3333
      HOST: 0.0.0.0
      APP_KEY: ${APP_KEY}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      LOG_LEVEL: debug
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - equilib_network

  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - equilib_network

networks:
  equilib_network:
    driver: bridge

volumes:
  postgres_data: